2018-05-08 16:30:10,754 ERROR: Exception on / [GET] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 23, in index
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2018-05-08 16:32:06,185 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:35]
2018-05-09 16:34:02,418 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:35]
2018-05-09 22:30:17,009 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-09 22:30:23,943 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-09 22:30:48,088 ERROR: Exception on /reset_password_request [POST] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 192, in reset_password_request
    send_password_reset_email(user)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/models.py", line 77, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2018-05-09 22:31:10,041 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-09 22:31:13,309 ERROR: Exception on /reset_password_request [POST] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 192, in reset_password_request
    send_password_reset_email(user)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/models.py", line 77, in get_reset_password_token
    application.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'application' is not defined
2018-05-09 22:31:20,530 ERROR: Exception on /reset_password_request [POST] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 192, in reset_password_request
    send_password_reset_email(user)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/models.py", line 77, in get_reset_password_token
    application.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'application' is not defined
2018-05-09 22:33:41,573 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-09 22:33:49,442 ERROR: Exception on /reset_password_request [POST] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 192, in reset_password_request
    send_password_reset_email(user)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 15, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2018-05-09 22:34:06,836 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
